---
- hosts: all
  become: yes
  tasks:
  - name: Ensure chrony is installed
    dnf:
      name: chrony
      state: present

  - name: Ensure chrony service is enabled and running
    service:
      name: chronyd
      state: started
      enabled: yes

  - name: Ensure tmux is installed
    dnf:
      name: tmux
      state: present
