# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  config.ssh.insert_key = false
  config.vm.synced_folder "." "/vagrant", disabled: true
  config.vm.provider :virtualbox do |v|
    v.memory = 512
    v.linked_clone = true
  end

  # Jump Box
  config.vm.define "jumpbox" do |app|
    app.vm.hostname = "jumpbox"
    app.vm.network :private_network, ip: "192.168.56.20"
  end
end
